name: health_care
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  awesome_dialog: ^3.2.0
  awesome_notifications: ^0.9.2
  awesome_top_snackbar: ^0.0.3
  bloc: ^8.1.3
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_database: ^10.5.7
  firebase_storage: ^11.2.6
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.1
  get: ^4.6.6
  getwidget: ^4.0.0
  google_maps_flutter: ^2.5.3
  gradient_icon: ^2.0.8
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  location: ^5.0.3
  meta: ^1.10.0
  modal_progress_hud_nsn: ^0.5.1
  pinput: ^3.0.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^26.1.38
  timezone: ^0.9.2
  uuid: ^4.3.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: "#0d2633"
    theme_color: "#0d2633"
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: assets/images/icon.png

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
