// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7kKm1d5UYmqQuSxDlQhcmThJp-w8dEg',
    appId: '1:849512846547:web:a172827353f3f7ade8f026',
    messagingSenderId: '849512846547',
    projectId: 'chat-app-a37e7',
    authDomain: 'chat-app-a37e7.firebaseapp.com',
    storageBucket: 'chat-app-a37e7.appspot.com',
    measurementId: 'G-8NDZZQDLGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFTpXAAPo_ZTxQ3ggwl0WzAHFrjz0Iss',
    appId: '1:849512846547:android:c0bc545306b034a1e8f026',
    messagingSenderId: '849512846547',
    projectId: 'chat-app-a37e7',
    storageBucket: 'chat-app-a37e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIli6ucucbqN9xRVb9KJtWCW1cRH_-kc',
    appId: '1:849512846547:ios:9225289c174e109ae8f026',
    messagingSenderId: '849512846547',
    projectId: 'chat-app-a37e7',
    storageBucket: 'chat-app-a37e7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJIli6ucucbqN9xRVb9KJtWCW1cRH_-kc',
    appId: '1:849512846547:ios:20fd79b4fe9c515de8f026',
    messagingSenderId: '849512846547',
    projectId: 'chat-app-a37e7',
    storageBucket: 'chat-app-a37e7.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
